name: Publish to NuGet

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TransactR.sln

      - name: Build
        run: dotnet build TransactR.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test TransactR.sln --no-build --configuration Release

      - name: Pack and publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          for proj in TransactR TransactR.Concordia TransactR.MediatR TransactR.EntityFramework TransactR.DistributedMemoryCache TransactR.MongoDB TransactR.AzureTableStorage
          do
            dotnet pack "$proj/$proj.csproj" --no-build --configuration Release --output .
            dotnet nuget push "$proj.*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json
          done
